[package]
name = "bevy_asky"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.0", default-features = false, features = [ "bevy_text", "bevy_ui", "default_font" ] }
bevy-alt-ui-navigation-lite = { version = "0.2.1", optional = true }
# bevy-ui-navigation = "0.33.1"
bevy_defer = { version = "0.12.1", optional = true }
futures = "0.3.30"
thiserror = "1.0.62"

[features]
async = [ "dep:bevy_defer" ]
focus = [ "dep:bevy-alt-ui-navigation-lite" ]

[dev-dependencies]
bevy = { version = "0.14.0" }
bevy-inspector-egui = "0.27.0"

[patch.crates-io]
# bevy-ui-navigation = { git = "https://github.com/shanecelis/ui-navigation.git", branch = "bevy-0.14" }

[[example]]
name = "text_async"
required-features = ["async"]
