[package]
name = "bevy_asky"
description = "A simple question-and-answer UI middleware for Bevy"
version = "0.5.0"
edition = "2024"
authors = ["Shane Celis <shane.celis@gmail.com>"]
keywords = [
    "bevy",
    "gamedev",
]
categories = [
    "game-development"
]
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/shanecelis/bevy_asky"

[dependencies]
accesskit = "0.24"
bevy = { version = "0.19", default-features = false, features = [ "bevy_text", "bevy_ui", "default_font", "std", "async_executor", "bevy_log", "bevy_input_focus", "keyboard", "mouse" ] }
bevy_a11y = "0.19"
bevy_defer = { version = "0.18", optional = true }
futures = { version = "0.3.30", optional = true }
thiserror = "2.0"

[features]
default = [ "color" ]
async = [ "dep:bevy_defer", "dep:futures" ]
button = []
color = []
ascii = []

[dev-dependencies]
bevy = "0.19"
bevy-inspector-egui = "0.36"
version-sync = "0.9.5"

[[example]]
name = "text-async"
path = "examples/async/text.rs"
required-features = ["async"]

[[example]]
name = "checkbox-group-async"
path = "examples/async/checkbox-group.rs"
required-features = ["async"]

[patch.crates-io]
bevy_defer = { path = "../bevy_defer" }
